language: node_js
node_js:
- '6'
script:
  - npm run test
  - npm run build
deploy:
  - provider: npm
    email: npm@farkas.land
    api_key:
      secure: PJL8xcTLBVf4NuqKmIoGKX4cwwA+yuv5BxHu6JvNNpL78OR1vZAiXQDWRv+ii8WtgD3tc6e5tNyyi/Xcu+/t4LvWzRvaG/Ije3FYGLSgsaH6gOv2p17voGGSSoGBJnwFKRDsDp1vY/8lppfbbyz5v1O8Sx/ohCFSrJntPn5KHffakwfKEHSYP5cOsYLdpyYRxR78RgV5Kv0PTdowtCWMsAuWOfIy+rulStR5Pl73NQp2PAegexg0ehgfCeQfcFXYZtk24WroNSJm9kMpJUSeGSBzmJoOWG8U/BNzqUN5QekhFjRTfG5bxkyLntao1QHaV2AMUz/ug+2xi9HM2+GnJxqPd8AZl0uxLe5Xl6cCqwn5q78bLPEtaAnXTuX/BC1bYSi4YQqwiCVNYNvbOGJYhjeNSD1J3aYYlMsSVXUxOOinQ0HaVo8qVB2BfV64Y7e0QfXCk0fuT9o0V88p18KfEoJFX3ZJK0Yp7gTp2ch8tdzw4kDf+TpTLqrIQfnzH0B9IiC6lFQAyXnNSH/2MtmefH64QPbsUmss1eNDzzwmkSyM4/xyto/0zEO9OBXRByAKLBhO6uk7g8IAdb7AVg/Jma+jG3SFolBn4Hgd4fqpY2pZEec+vLl5HP+PXHyY8tbrujMFTzhnYCyyoqRcJ3x8sRLEB26xifK18mFgnVdRC7Y=
    on:
      tags: true
      repo: zsfarkas/ng2-alert-center
  - provider: cloudfoundry
    edge: true
    username: pivotal@farkas.land
    password:
      secure: BTh/c3GVdaOAOllTukL1Ov92NSI+84b99J/hW/C8WXCmaE6iK2uVdH2mdqjUHL//BSckNf0BFfxmKxqcCPsd48yELFd6SDnbPC19TvdmMwJYNMzIQPyQyei5hW7rz5nK8UUy7OXEcZdr3L3dzcijp1DmlinnPidSzUfysYqB0OazZSjRTGSA+c244mMz6XOxGJEmeD3oqgOTegtH/NIVFvqQNuz+i6m92lN/Eh3VVO6NkMKfk6um4ftSMzRi3RC94cA3+335WvnssacwGJzw8HmVoYkjjajpcgZTug919ni86JcsOB8qPnEn1xrnQzseaq1sLY0uMh00mmUmDegkSd3slDflO79Jd1JWQZ80PnCz6LDk4FXt1aqCQAGKvOORL0ccZW3BYEmas45SBp1vV6rECPEgVdeaYa8JlKcHGDngoShkHiEyPV1BfQclOrb96N44KqwD/twB3cq5gCUdLPqdW7juwTVSxM/6mUEr5CWn7WPpvloh4N+jpPf4FAfz8GBqEtKEFd+K81hfHflNKDLFQtlynEUWk9yYT1HslQWge5yneABZjF45h7h1Dlqbuv94MF43yrrGDZYmCxth3vWrug0rpU/Y/5VKfcBDQF5VcqLLi0+b5tIBI17Q2sWaKZUJRdj5AyE/Ox4ypb9Qna370oHrTAffi35lB1pIIR4=
    api: https://api.run.pivotal.io
    organization: farkas-land
    space: development
